// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GigWeb.Data.RazorPagesMigrations
{
    [DbContext(typeof(RazorPagesEventContext))]
    [Migration("20200602213433_Invitations")]
    partial class Invitations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GigWeb.Models.Invitation", b =>
                {
                    b.Property<int>("invitation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("PurchaseDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Sha512key")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("event_id")
                        .HasColumnType("integer");

                    b.Property<int?>("targetzone_id")
                        .HasColumnType("integer");

                    b.HasKey("invitation_id");

                    b.HasIndex("targetzone_id");

                    b.ToTable("Invitation");
                });

            modelBuilder.Entity("GigWeb.Models.Zone", b =>
                {
                    b.Property<int>("zone_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("zone_event_id")
                        .HasColumnType("integer");

                    b.HasKey("zone_id");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("GigWeb.Models.Invitation", b =>
                {
                    b.HasOne("GigWeb.Models.Zone", "target")
                        .WithMany()
                        .HasForeignKey("targetzone_id");
                });
#pragma warning restore 612, 618
        }
    }
}
